# Generated by Django 3.2.8 on 2021-10-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(blank=True, max_length=200, null=True)),
                ('nabywca_taxid', models.CharField(blank=True, max_length=20, null=True)),
                ('nabywca_adres', models.TextField(blank=True, null=True)),
                ('sprzedawca_taxid', models.TextField(blank=True, null=True)),
                ('sprzedawca_adres', models.TextField(blank=True, null=True)),
                ('data_sprzedazy', models.DateField(verbose_name='Data sprzedaży')),
                ('data_wystawienia', models.DateField(verbose_name='Data wystawienia')),
                ('is_oplacona', models.BooleanField(default=False)),
                ('is_kosztowa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
            },
        ),
        migrations.CreateModel(
            name='JednostkaMiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=100)),
                ('Nazwisko', models.CharField(max_length=100)),
                ('nr_pesel', models.TextField(max_length=11)),
                ('Adres', models.CharField(max_length=150)),
                ('kod_pocztowy', models.TextField(max_length=6)),
                ('miasto', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('nr_telefonu', models.TextField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Podatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15, unique=True)),
                ('stawka', models.DecimalField(decimal_places=2, default=0, max_digits=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprzedawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sprzedawca_nazwa', models.CharField(max_length=100)),
                ('Sprzedawca_adres', models.CharField(max_length=100)),
                ('Sprzedawca_podatek', models.CharField(max_length=20)),
                ('Sprzedawca_data_zalozenia', models.DateField(verbose_name='Data założenia')),
                ('Sprzedawca_telefon', models.TextField()),
                ('Sprzedawca_NIP', models.TextField()),
                ('Sprzedawca_wlasciciel', models.TextField()),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Sprzedawcy',
            },
        ),
        migrations.CreateModel(
            name='PozycjaFaktury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wartosc_netto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wartosc_all', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakir.faktura')),
                ('jednostka_miary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakir.jednostkamiary')),
                ('podatek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakir.podatek')),
            ],
        ),
        migrations.AddField(
            model_name='faktura',
            name='nabywca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabywcy_set', to='fakir.sprzedawca'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='sprzedawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprzedawcy_set', to='fakir.sprzedawca'),
        ),
    ]
