# Generated by Django 3.2.8 on 2021-10-29 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0002_auto_20211029_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprzedawca',
            name='Sprzedawca_telefon',
        ),
        migrations.RemoveField(
            model_name='sprzedawca',
            name='Sprzedawca_wlasciciel',
        ),
        migrations.AddField(
            model_name='sprzedawca',
            name='Sprzedawca_numer',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jednostkamiary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kod_pocztowy',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nr_pesel',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='pesel musi miec 11 liter', regex='^\\+?1?\\d{0,11}$')]),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nr_telefonu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='podatek',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pozycjafaktury',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='Sprzedawca_NIP',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Nip must have 10 digits', regex='^\\+?1?\\d{0,10}$')]),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='Sprzedawca_podatek',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
