# Generated by Django 3.2.8 on 2021-10-29 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0003_auto_20211029_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='nr_pesel',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='pesel musi miec 11 liter', regex='^\\+?1?\\d{11,11}$')]),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='Sprzedawca_NIP',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Nip must have 10 digits', regex='^\\+?1?\\d{10,10}$')]),
        ),
    ]
