# Generated by Django 3.2.8 on 2021-10-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0004_auto_20211029_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='nabywca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabywcy_set', to='fakir.klient'),
        ),
    ]
